name: Build and Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Upload JAR Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-jar
          path: target/*.jar

      - name: Upload classes Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-classes
          path: target/classes/

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn -B test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

  code-quality:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Download classes Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-classes
          path: target/classes/

      # - name: Run Checkstyle

      # - name: Upload Checkstyle Results

      - name: Run SpotBugs
        run: mvn spotbugs:check

      - name: Upload SpotBugs Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-results
          path: target/spotbugsXml.xml

  deploy:
    needs: [test, code-quality]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Download JAR Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-jar
          path: target/

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SPRING_APP_SSH_KEY }}

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SPRING_APP_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          scp target/demo-0.0.1-SNAPSHOT.jar ${{ secrets.SPRING_APP_USER }}@${{ secrets.SPRING_APP_HOST }}:/home/${{ secrets.SPRING_APP_USER }}/app/app.jar

      - name: Start Application
        run: |
          ssh ${{ secrets.SPRING_APP_USER }}@${{ secrets.SPRING_APP_HOST }} << 'ENDSSH'
            sudo systemctl restart spring-app
            sudo systemctl status spring-app --no-pager
          ENDSSH
